application:
    jwt:
      secretKey: "QARFHTVWEFKHDFGO;IE;OIJWEW;OWJIEWFIH!@#"
      tokenPrefix: "Bearer "
      tokenExpirationAfterHours: 1
      tokenExpirationAfterDays: 1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/miniprojetjee"
    username: "user"
    password: "user@"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect